namespace StressedBread.Drinks.Models.DTOs;
internal class DrinkDetailDTO
{
    internal string Name { get; set; } = string.Empty;
    internal string Category { get; set; } = string.Empty;
    internal string Alcoholic { get; set; } = string.Empty;
    internal string Glass { get; set; } = string.Empty;
    internal string Instructions { get; set; } = string.Empty;
    internal string DrinkThumb { get; set; } = string.Empty;
    internal string Ingredient1 { get; set; } = string.Empty;
    internal string Ingredient2 { get; set; } = string.Empty;
    internal string Ingredient3 { get; set; } = string.Empty;
    internal string Ingredient4 { get; set; } = string.Empty;
    internal string Ingredient5 { get; set; } = string.Empty;
    internal string Ingredient6 { get; set; } = string.Empty;
    internal string Ingredient7 { get; set; } = string.Empty;
    internal string Ingredient8 { get; set; } = string.Empty;
    internal string Ingredient9 { get; set; } = string.Empty;
    internal string Ingredient10 { get; set; } = string.Empty;
    internal string Ingredient11 { get; set; } = string.Empty;
    internal string Ingredient12 { get; set; } = string.Empty;
    internal string Ingredient13 { get; set; } = string.Empty;
    internal string Ingredient14 { get; set; } = string.Empty;
    internal string Ingredient15 { get; set; } = string.Empty;
    internal string Measure1 { get; set; } = string.Empty;
    internal string Measure2 { get; set; } = string.Empty;
    internal string Measure3 { get; set; } = string.Empty;
    internal string Measure4 { get; set; } = string.Empty;
    internal string Measure5 { get; set; } = string.Empty;
    internal string Measure6 { get; set; } = string.Empty;
    internal string Measure7 { get; set; } = string.Empty;
    internal string Measure8 { get; set; } = string.Empty;
    internal string Measure9 { get; set; } = string.Empty;
    internal string Measure10 { get; set; } = string.Empty;
    internal string Measure11 { get; set; } = string.Empty;
    internal string Measure12 { get; set; } = string.Empty;
    internal string Measure13 { get; set; } = string.Empty;
    internal string Measure14 { get; set; } = string.Empty;
    internal string Measure15 { get; set; } = string.Empty;
}
